### ISSUE TITLE
Next.XP 2.0.0 release

### ISSUE THREAD

**Issue by pmi** [enonic/nextxp-demo#651]
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/nextjs-adapter/issues/279
- [ ] https://github.com/enonic/nextxp-demo/issues/674
- [ ] https://github.com/enonic/nextxp-demo/issues/675
- [ ] https://github.com/enonic/nextxp-demo/issues/676
- [ ] https://github.com/enonic/nextxp-demo/issues/677
- [ ] https://github.com/enonic/nextxp-demo/issues/691
- [ ] https://github.com/enonic/nextxp-demo/issues/692
- [x] Update cloud template for Next.XP
- [ ] https://github.com/enonic/nextxp-demo/issues/703
- [ ] https://github.com/enonic/nextxp-demo/issues/707
```
